/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Mateus Moura
 */
public class FerramentasAdministrativas extends javax.swing.JFrame {

    /**
     * Creates new form FerramentasAdministrativas
     */
    public FerramentasAdministrativas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCadastarCliente = new javax.swing.JButton();
        btCadastrarConta = new javax.swing.JButton();
        btAtualizarCadastroCliente = new javax.swing.JButton();
        btAtualizarCadastroConta = new javax.swing.JButton();
        btRemoverCliente = new javax.swing.JButton();
        btRemoverConta = new javax.swing.JButton();
        btVisualizarContasCriadas = new javax.swing.JButton();
        btVisualizarClientesCadastrados = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        bmMenu = new javax.swing.JMenuBar();
        bmCadastrar = new javax.swing.JMenu();
        bmCadastrarCliente = new javax.swing.JMenuItem();
        bmCadastrarConta = new javax.swing.JMenuItem();
        bmAtualizar = new javax.swing.JMenu();
        bmAtualizarCadastroCliente = new javax.swing.JMenuItem();
        bmAtualizarInformacoesConta = new javax.swing.JMenuItem();
        bmRemover = new javax.swing.JMenu();
        bmRemoverCliente = new javax.swing.JMenuItem();
        bmRemoverConta = new javax.swing.JMenuItem();
        bmVisualizar = new javax.swing.JMenu();
        bmVisualizarContasCriadas = new javax.swing.JMenuItem();
        VisualizarClientesCadastrados = new javax.swing.JMenuItem();
        bmSistema = new javax.swing.JMenu();
        bmAjuda = new javax.swing.JMenuItem();
        bmSobre = new javax.swing.JMenuItem();
        bmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FERRAMENTAS ADMINISTRATIVAS");

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        btCadastarCliente.setBackground(new java.awt.Color(156, 150, 157));
        btCadastarCliente.setText("Cadastrar Cliente");
        btCadastarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastarClienteActionPerformed(evt);
            }
        });

        btCadastrarConta.setBackground(new java.awt.Color(156, 150, 157));
        btCadastrarConta.setText("Cadastrar Conta");
        btCadastrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarContaActionPerformed(evt);
            }
        });

        btAtualizarCadastroCliente.setBackground(new java.awt.Color(156, 150, 157));
        btAtualizarCadastroCliente.setText("Atualizar Cadastro do Cliente");

        btAtualizarCadastroConta.setBackground(new java.awt.Color(156, 150, 157));
        btAtualizarCadastroConta.setText("Atualizar Informações da Conta");

        btRemoverCliente.setBackground(new java.awt.Color(156, 150, 157));
        btRemoverCliente.setText("Remover Cliente");

        btRemoverConta.setBackground(new java.awt.Color(156, 150, 157));
        btRemoverConta.setText("Remover Conta");

        btVisualizarContasCriadas.setBackground(new java.awt.Color(156, 150, 157));
        btVisualizarContasCriadas.setText("Visualizar Contas Criadas");

        btVisualizarClientesCadastrados.setBackground(new java.awt.Color(156, 150, 157));
        btVisualizarClientesCadastrados.setText("Visualizar Clientes Cadastrados");

        jDesktopPane2.setBackground(new java.awt.Color(153, 255, 204));
        jDesktopPane2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btCadastarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCadastrarConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAtualizarCadastroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAtualizarCadastroConta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btRemoverCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btRemoverConta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVisualizarContasCriadas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVisualizarClientesCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jDesktopPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastarCliente)
                    .addComponent(btCadastrarConta)
                    .addComponent(btAtualizarCadastroCliente)
                    .addComponent(btAtualizarCadastroConta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRemoverCliente)
                    .addComponent(btRemoverConta)
                    .addComponent(btVisualizarContasCriadas)
                    .addComponent(btVisualizarClientesCadastrados))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );

        bmMenu.setBackground(new java.awt.Color(10, 69, 53));

        bmCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bmCadastrar.setText("Cadastrar");

        bmCadastrarCliente.setText("Cadastrar Cliente");
        bmCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmCadastrarClienteActionPerformed(evt);
            }
        });
        bmCadastrar.add(bmCadastrarCliente);

        bmCadastrarConta.setText("Cadastrar Conta");
        bmCadastrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmCadastrarContaActionPerformed(evt);
            }
        });
        bmCadastrar.add(bmCadastrarConta);

        bmMenu.add(bmCadastrar);

        bmAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        bmAtualizar.setText("Atualizar");

        bmAtualizarCadastroCliente.setText("Atualizar Cadastro do Cliente");
        bmAtualizar.add(bmAtualizarCadastroCliente);

        bmAtualizarInformacoesConta.setText("Atualizar Informações da Conta");
        bmAtualizar.add(bmAtualizarInformacoesConta);

        bmMenu.add(bmAtualizar);

        bmRemover.setForeground(new java.awt.Color(255, 255, 255));
        bmRemover.setText("Remover");

        bmRemoverCliente.setText("Remover Cliente");
        bmRemover.add(bmRemoverCliente);

        bmRemoverConta.setText("Remover Conta");
        bmRemover.add(bmRemoverConta);

        bmMenu.add(bmRemover);

        bmVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        bmVisualizar.setText("Visualizar");

        bmVisualizarContasCriadas.setText("Visualizar Contas Criadas");
        bmVisualizar.add(bmVisualizarContasCriadas);

        VisualizarClientesCadastrados.setText("Visualizar Clientes Cadastrados");
        bmVisualizar.add(VisualizarClientesCadastrados);

        bmMenu.add(bmVisualizar);

        bmSistema.setForeground(new java.awt.Color(255, 255, 255));
        bmSistema.setText("Sistema");

        bmAjuda.setText("Ajuda");
        bmSistema.add(bmAjuda);

        bmSobre.setText("Sobre");
        bmSistema.add(bmSobre);

        bmSair.setText("Sair");
        bmSistema.add(bmSair);

        bmMenu.add(bmSistema);

        setJMenuBar(bmMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastarClienteActionPerformed
       gui.CadastrarCliente cc = new CadastrarCliente();
       jDesktopPane2.add(cc);
       cc.setVisible(true);        
    }//GEN-LAST:event_btCadastarClienteActionPerformed

    private void btCadastrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarContaActionPerformed
       gui.CadastrarConta cc = new CadastrarConta();        
       cc.setVisible(true);        
    }//GEN-LAST:event_btCadastrarContaActionPerformed

    private void bmCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmCadastrarClienteActionPerformed
       gui.CadastrarCliente cc = new CadastrarCliente();
       jDesktopPane2.add(cc);
       cc.setVisible(true);
    }//GEN-LAST:event_bmCadastrarClienteActionPerformed

    private void bmCadastrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmCadastrarContaActionPerformed
       gui.CadastrarConta cc = new CadastrarConta();      
       cc.setVisible(true);
    }//GEN-LAST:event_bmCadastrarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FerramentasAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FerramentasAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FerramentasAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FerramentasAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FerramentasAdministrativas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem VisualizarClientesCadastrados;
    private javax.swing.JMenuItem bmAjuda;
    private javax.swing.JMenu bmAtualizar;
    private javax.swing.JMenuItem bmAtualizarCadastroCliente;
    private javax.swing.JMenuItem bmAtualizarInformacoesConta;
    private javax.swing.JMenu bmCadastrar;
    private javax.swing.JMenuItem bmCadastrarCliente;
    private javax.swing.JMenuItem bmCadastrarConta;
    private javax.swing.JMenuBar bmMenu;
    private javax.swing.JMenu bmRemover;
    private javax.swing.JMenuItem bmRemoverCliente;
    private javax.swing.JMenuItem bmRemoverConta;
    private javax.swing.JMenuItem bmSair;
    private javax.swing.JMenu bmSistema;
    private javax.swing.JMenuItem bmSobre;
    private javax.swing.JMenu bmVisualizar;
    private javax.swing.JMenuItem bmVisualizarContasCriadas;
    private javax.swing.JButton btAtualizarCadastroCliente;
    private javax.swing.JButton btAtualizarCadastroConta;
    private javax.swing.JButton btCadastarCliente;
    private javax.swing.JButton btCadastrarConta;
    private javax.swing.JButton btRemoverCliente;
    private javax.swing.JButton btRemoverConta;
    private javax.swing.JButton btVisualizarClientesCadastrados;
    private javax.swing.JButton btVisualizarContasCriadas;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
