/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Mateus Moura
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAcessoAdministrativo = new javax.swing.JButton();
        btAcessoCliente = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        bmAdministrativo = new javax.swing.JMenu();
        bmCadastrar = new javax.swing.JMenuItem();
        bmSistema = new javax.swing.JMenu();
        bmAjuda = new javax.swing.JMenuItem();
        bmSobre = new javax.swing.JMenuItem();
        bmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANCO VISION");
        setBackground(new java.awt.Color(10, 69, 53));

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        btAcessoAdministrativo.setBackground(new java.awt.Color(0, 204, 204));
        btAcessoAdministrativo.setText("Acesso Administrativo");
        btAcessoAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessoAdministrativoActionPerformed(evt);
            }
        });

        btAcessoCliente.setBackground(new java.awt.Color(0, 204, 204));
        btAcessoCliente.setText("Acesso Cliente");
        btAcessoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAcessoAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(btAcessoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAcessoAdministrativo)
                    .addComponent(btAcessoCliente))
                .addContainerGap())
        );

        BarraMenu.setBackground(new java.awt.Color(10, 69, 53));
        BarraMenu.setBorder(null);

        bmAdministrativo.setForeground(new java.awt.Color(255, 255, 255));
        bmAdministrativo.setText("Administrativo");

        bmCadastrar.setText("Ferramentas Adminstrativas");
        bmAdministrativo.add(bmCadastrar);

        BarraMenu.add(bmAdministrativo);

        bmSistema.setForeground(new java.awt.Color(255, 255, 255));
        bmSistema.setText("Sistema");

        bmAjuda.setText("Ajuda");
        bmAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmAjudaActionPerformed(evt);
            }
        });
        bmSistema.add(bmAjuda);

        bmSobre.setText("Sobre");
        bmSistema.add(bmSobre);

        bmSair.setText("Sair");
        bmSistema.add(bmSair);

        BarraMenu.add(bmSistema);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcessoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessoClienteActionPerformed
        gui.LoginCliente lc = new gui.LoginCliente();        
        lc.setVisible(true);            
    }//GEN-LAST:event_btAcessoClienteActionPerformed

    private void btAcessoAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessoAdministrativoActionPerformed
        gui.Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btAcessoAdministrativoActionPerformed

    private void bmAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu bmAdministrativo;
    private javax.swing.JMenuItem bmAjuda;
    private javax.swing.JMenuItem bmCadastrar;
    private javax.swing.JMenuItem bmSair;
    private javax.swing.JMenu bmSistema;
    private javax.swing.JMenuItem bmSobre;
    private javax.swing.JButton btAcessoAdministrativo;
    private javax.swing.JButton btAcessoCliente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
